name: Build

on:
  workflow_run:
    workflows: [Prerelease]
    types:
      - completed

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: public.ecr.aws/y6a1b9z5

jobs:
  build-and-push:
    name: Build & Push Rails and React Images
    runs-on: ubuntu-latest
    environment:
      name: sandbox
      url: http://my-blog-app-service:3001

    if: |
        (github.event_name != 'workflow_run') ||
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          # aws-region: ${{ env.AWS_REGION }}
          # aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build & Push Rails API Docker image (multi-arch)
        env:
          # REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REPOSITORY: my-blog-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "🚀 Build and Push Rails API"
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $ECR_REGISTRY/$REPOSITORY:latest \
            -f Dockerfile.api \
            --push .

      - name: Build & Push React App Docker image (multi-arch)
        env:
          # REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REPOSITORY: my-blog-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "🚀 Build and Push React App"
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg REACT_APP_API_URL=http://my-blog-api-service:3000/graphql \
            -t $ECR_REGISTRY/$REPOSITORY:latest \
            -f Dockerfile.app \
            --push .

      # - name: Build Rails API Docker image
      #   run: |
      #     echo "🚀 Build and Push Rails API"
      #     docker build -f Dockerfile.api -t my-blog-api .

      # - name: Tag and push Rails API image to ECR
      #   run: |
      #     docker tag my-blog-api:latest $ECR_REGISTRY/my-blog-api:latest
      #     docker push $ECR_REGISTRY/my-blog-api:latest
