name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows: [Build]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: public.ecr.aws/y6a1b9z5

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    environment:
      name: sandbox
      url: http://my-blog-app-service:3001
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: |
          echo "🚀 Terraform init"
          terraform init

      - name: Terraform plan
        run: |
          echo "🚀 Terraform plan"
          terraform plan -out=tfplan

      - name: Terraform apply
        run: |
          echo "🚀 Terraform apply"
          terraform apply -var="create_ecr_repo=false" -auto-approve tfplan
